import { z } from "zod";

export const businessObjectTypeSchema = z.enum([
  "party",
  "master",
  "reference",
  "transaction",
  "case",
  "request",
  "decision",
  "document",
  "event",
  "financial",
  "position",
  "instruction",
  "report",
  "evidence",
  "analytical",
  "abstract"
]);

export const canonicalBusinessObjectSchema = z.object({
  id: z.string().regex(/^RAIA-BO-\d{4}$/),
  slug: z.string(),
  nameEs: z.string(),
  nameEn: z.string().optional(),
  shortName: z.string().optional(),
  aliases: z.array(z.string()),
  definition: z.string(),
  businessMeaning: z.string(),
  purpose: z.string(),
  objectType: businessObjectTypeSchema,
  informationDomainId: z.string().optional(),
  conceptIds: z.array(z.string()),
  abstract: z.boolean(),
  specializationOfId: z.string().optional(),
  specializationIds: z.array(z.string()),
  identifierAttributeIds: z.array(z.string()),
  attributeIds: z.array(z.string()),
  relationshipIds: z.array(z.string()),
  invariantIds: z.array(z.string()),
  producerServiceDomainIds: z.array(z.string()),
  authoritativeServiceDomainIds: z.array(z.string()),
  consumerServiceDomainIds: z.array(z.string()),
  validatingServiceDomainIds: z.array(z.string()),
  serviceOperationIds: z.array(z.string()),
  businessEventIds: z.array(z.string()),
  businessScenarioIds: z.array(z.string()),
  controlRecordIds: z.array(z.string()),
  accountableParticipantIds: z.array(z.string()),
  stewardRoleIds: z.array(z.string()),
  classificationIds: z.array(z.string()),
  qualityRuleIds: z.array(z.string()),
  lifecyclePolicyId: z.string().optional(),
  retentionPolicyIds: z.array(z.string()),
  controlIds: z.array(z.string()),
  evidenceIds: z.array(z.string()),
  regulatoryMappingIds: z.array(z.string()),
  criticality: z.enum(["low", "medium", "high", "systemic"]),
  status: z.enum(["draft", "proposed", "reviewed", "validated", "deprecated"]),
  confidence: z.enum(["low", "medium", "high"]),
  replacementObjectId: z.string().optional(),
  deprecationReason: z.string().optional(),
  assumptions: z.array(z.string()),
  unresolvedQuestions: z.array(z.string()),
  version: z.string(),
  createdAt: z.string(),
  updatedAt: z.string()
});
