import { z } from "zod";

export const lifecycleStatusSchema = z.enum(["draft", "proposed", "reviewed", "validated", "deprecated"]);

export const informationDomainSchema = z.object({
  id: z.string().regex(/^RAIA-IDOM-\d{3}$/),
  slug: z.string(),
  nameEs: z.string(),
  nameEn: z.string().optional(),
  description: z.string(),
  purpose: z.string(),
  semanticBoundary: z.string(),
  parentDomainId: z.string().regex(/^RAIA-IDOM-\d{3}$/).optional(),
  childDomainIds: z.array(z.string().regex(/^RAIA-IDOM-\d{3}$/)),
  informationConceptIds: z.array(z.string().regex(/^RAIA-ICON-\d{3}$/)),
  businessObjectIds: z.array(z.string().regex(/^RAIA-BO-\d{3}$/)),
  informationAssetIds: z.array(z.string().regex(/^RAIA-IAST-\d{3}$/)),
  dataProductIds: z.array(z.string().regex(/^RAIA-DPRD-\d{3}$/)),
  accountableParticipantIds: z.array(z.string()),
  ownerRoleIds: z.array(z.string()),
  stewardRoleIds: z.array(z.string()),
  custodianRoleIds: z.array(z.string()),
  serviceDomainIds: z.array(z.string().regex(/^RAIA-SD-\d{3}$/)),
  businessScenarioIds: z.array(z.string().regex(/^RAIA-BS-\d{4}$/)),
  regulatoryMappingIds: z.array(z.string()),
  controlIds: z.array(z.string()),
  criticality: z.enum(["low", "medium", "high", "systemic"]),
  status: lifecycleStatusSchema,
  version: z.string(),
  createdAt: z.string(),
  updatedAt: z.string()
});

export const informationConceptSchema = z.object({
  id: z.string().regex(/^RAIA-ICON-\d{3}$/),
  slug: z.string(),
  nameEs: z.string(),
  nameEn: z.string().optional(),
  aliases: z.array(z.string()),
  definition: z.string(),
  businessMeaning: z.string(),
  informationDomainId: z.string().regex(/^RAIA-IDOM-\d{3}$/),
  broaderConceptId: z.string().regex(/^RAIA-ICON-\d{3}$/).optional(),
  narrowerConceptIds: z.array(z.string().regex(/^RAIA-ICON-\d{3}$/)),
  relatedConceptIds: z.array(z.string().regex(/^RAIA-ICON-\d{3}$/)),
  businessObjectIds: z.array(z.string().regex(/^RAIA-BO-\d{3}$/)),
  accountableParticipantIds: z.array(z.string()),
  stewardRoleIds: z.array(z.string()),
  regulatoryMappingIds: z.array(z.string()),
  semanticStatus: z.enum(["candidate", "canonical", "synonym", "deprecated"]),
  replacementConceptId: z.string().regex(/^RAIA-ICON-\d{3}$/).optional(),
  deprecationReason: z.string().optional(),
  version: z.string(),
  createdAt: z.string(),
  updatedAt: z.string()
});

export const canonicalBusinessObjectSchema = z.object({
  id: z.string().regex(/^RAIA-BO-\d{3}$/),
  slug: z.string(),
  nameEs: z.string(),
  nameEn: z.string().optional(),
  aliases: z.array(z.string()),
  description: z.string(),
  businessMeaning: z.string(),
  informationDomainId: z.string().regex(/^RAIA-IDOM-\d{3}$/),
  conceptIds: z.array(z.string().regex(/^RAIA-ICON-\d{3}$/)),
  objectType: z.enum([
    "master",
    "transaction",
    "reference",
    "event",
    "document",
    "control",
    "evidence",
    "analytical"
  ]),
  identifierAttributeIds: z.array(z.string()),
  attributeIds: z.array(z.string()),
  parentObjectId: z.string().regex(/^RAIA-BO-\d{3}$/).optional(),
  childObjectIds: z.array(z.string().regex(/^RAIA-BO-\d{3}$/)),
  relatedObjectIds: z.array(z.string().regex(/^RAIA-BO-\d{3}$/)),
  producerServiceDomainIds: z.array(z.string().regex(/^RAIA-SD-\d{3}$/)),
  consumerServiceDomainIds: z.array(z.string().regex(/^RAIA-SD-\d{3}$/)),
  authoritativeServiceDomainIds: z.array(z.string().regex(/^RAIA-SD-\d{3}$/)),
  businessScenarioIds: z.array(z.string().regex(/^RAIA-BS-\d{4}$/)),
  businessEventIds: z.array(z.string()),
  classificationIds: z.array(z.string().regex(/^RAIA-ICLAS-\d{3}$/)),
  qualityRuleIds: z.array(z.string().regex(/^RAIA-IQR-\d{3}$/)),
  lifecyclePolicyId: z.string().regex(/^RAIA-ILCP-\d{3}$/).optional(),
  retentionPolicyIds: z.array(z.string().regex(/^RAIA-IRTP-\d{3}$/)),
  regulatoryMappingIds: z.array(z.string()),
  controlIds: z.array(z.string()),
  status: lifecycleStatusSchema,
  version: z.string(),
  createdAt: z.string(),
  updatedAt: z.string()
});
